fix: add missing get parameter to syncStore Zustand creator
create((set) => ... called get().lastSynced on line 25, causing
ReferenceError: get is not defined when clicking Sync.